----------CICLO 1: Acciones Referenciales

/*Al eliminar la FK_SANCION_AGENTETRANSITO se deja el valor de null para la FK  */
ALTER TABLE SANCION ADD CONSTRAINT FK_SANCION_AGENTETRANSITO FOREIGN KEY(AGENTE) REFERENCES AGENTETRANSITO(IDAGENTE) ON DELETE NULL;
/*Al eliminar la FK_TIENE_CIUDADANO se deja el valor de null para la FK  */
ALTER TABLE TIENE ADD CONSTRAINT FK_TIENE_CIUDADANO FOREIGN KEY(CIUDADANO) REFERENCES CIUDADANO(NUMEROID) ON DELETE NULL;
