----------CICLO 1: Atributos
ALTER TABLE AGENTETRANSITO MODIFY(CORREO CHECK(CORREO LIKE '%@%.%'));
ALTER TABLE AGENTETRANSITO MODIFY(IDENTIFICACION CHECK(IDENTIFICACION='CC' OR IDENTIFICACION='CE'));
ALTER TABLE CIUDADANO MODIFY(CORREO CHECK(CORREO LIKE '%@%.%'));
ALTER TABLE CIUDADANO MODIFY(IDENTIFICACION CHECK(IDENTIFICACION='CC' OR IDENTIFICACION='CE'));
ALTER TABLE CIUDADANO MODIFY(TELEFONO CHECK(TELEFONO LIKE'3%'));
ALTER TABLE SANCION MODIFY(TIPO CHECK(TIPO='A' OR TIPO='M' OR TIPO='I' OR TIPO='S' OR TIPO='R' OR TIPO='C'));
ALTER TABLE VEHICULO MODIFY(TIPOVEHICULO CHECK(TIPOVEHICULO='GRUA' OR TIPOVEHICULO='REVISIÓN' OR TIPOVEHICULO='CAPACITACIÓN' OR TIPOVEHICULO='RESCATE' OR TIPOVEHICULO='PATRULLA' OR TIPOVEHICULO='MOTOCICLETA' OR TIPOVEHICULO='PARTICULAR' OR TIPOVEHICULO='CARGA' OR TIPOVEHICULO='PASAJEROS'));
ALTER TABLE VEHICULO MODIFY(TIPOVEHICULO CHECK(REGEXP_LIKE(TIPOVEHICULO,'^([A-Z0-9]*)$')AND UPPER(TIPOVEHICULO)=TIPOVEHICULO));






------------------------POBLARNOOK-------------------------------------------
/*
 *Se está insertando una identificación incorrecta
 */
 
INSERT INTO AGENTETRANSITO VALUES(1,'TI',1012554,'Cuadrante1','zara@hotmail.com');
/*
 *Se está insertando un correo incorrecto
 */
 
INSERT INTO AGENTETRANSITO VALUES(1,'CE',1012447022,'Cuadrante2','santihotmail.com');
 
/*
 *Se está insertando un telefono que no empieza por 3
 */
 
INSERT INTO CIUDADANO VALUES(1,'CE','Jennifer Sandoval','jenn222@gmail.com','4567890321');

/*
 *Se está insertando un correo incorrecto
 */
 
INSERT INTO CIUDADANO VALUES(2,'CC','Cristina Diaz','cristina@gmailcom','3214567890');

/*
 *Se está insertando una identificación incorrecta
 */
 
INSERT INTO CIUDADANO VALUES(3,'NIT','Felipe Diaz','felipe234@gmail.com','3216543217');

DESC AGENTETRANSITO;

------------------------POBLAROK-------------------------------------------

INSERT INTO AGENTETRANSITO VALUES(4,'CE',101244702,1,'santi@hotmail.com');
INSERT INTO CIUDADANO VALUES(1,'CE','Jennifer Sandoval','jenn222@gmail.com',null);
INSERT INTO CIUDADANO VALUES(2,'CC','Cristina Diaz','cristina@gmail.com','3214567890');
INSERT INTO CIUDADANO VALUES(3,'CC','Felipe Diaz','felipe234@gmail.com','3216543217');

SELECT * FROM AGENTETRANSITO;

DESC CIUDADANO;