---------CICLO 1: XPoblar(Eliminar los datos)

DELETE FROM VEHICULO;
DELETE FROM TIENE;
DELETE FROM CIUDADANO;
DELETE FROM SANCION;
DELETE FROM AGENTETRANSITO;
DELETE FROM SITIO;

------XTABLAS-------

DROP TABLE VEHICULO;
DROP TABLE TIENE;
DROP TABLE SANCION;
DROP TABLE SITIO;
DROP TABLE CIUDADANO;
DROP TABLE AGENTETRANSITO;

