----------Disparadores------------
CREATE OR REPLACE TRIGGER ID_AGENTE
BEFORE INSERT ON AGENTETRANSITO
FOR EACH ROW
DECLARE
    consec NUMBER;
BEGIN
    SELECT (MAX(IDAGENTE)) INTO consec FROM AGENTETRANSITO;
    IF consec IS NULL THEN
        :NEW.IDAGENTE := 1;
    ELSE
        :NEW.IDAGENTE := consec+1;
    END IF;
END;



CREATE OR REPLACE TRIGGER ID_SANCION
BEFORE INSERT ON SANCION
FOR EACH ROW
DECLARE
    consec NUMBER;
BEGIN
    SELECT (MAX(IDSANCION)) INTO consec FROM SANCION;
    IF consec IS NULL THEN
        :NEW.IDSANCION := 1;
    ELSE
        :NEW.IDSANCION := consec+1;
    END IF;
END;



CREATE OR REPLACE TRIGGER ID_SITIO
BEFORE INSERT ON SITIO
FOR EACH ROW
DECLARE
    consec NUMBER;
BEGIN
    SELECT (MAX(IDSITIO)) INTO consec FROM SITIO;
    IF consec IS NULL THEN
        :NEW.IDSITIO := 1;
    ELSE
        :NEW.IDSITIO := consec+1;
    END IF;
END;


CREATE OR REPLACE TRIGGER CIUDADANO_TEL
AFTER INSERT ON CIUDADANO
FOR EACH ROW
BEGIN
     
     IF :NEW.TELEFONO IS NULL THEN
        UPDATE CIUDADANO SET TELEFONO='NO TIENE'; 
    END IF;
END;



CREATE OR REPLACE TRIGGER ELI_SANCION
BEFORE DELETE ON SANCION
FOR EACH ROW
BEGIN 
    raise_application_error(-20007,'No se pueden eliminar las sanciones');
END;


CREATE OR REPLACE TRIGGER ELI_CIUDADANO
BEFORE DELETE ON CIUDADANO
FOR EACH ROW
BEGIN 
    raise_application_error(-20007,'No se pueden eliminar los ciudadanos');
END;


CREATE OR REPLACE TRIGGER FECHA_SANCION
BEFORE INSERT ON TIENE
FOR EACH ROW
BEGIN
    :NEW.FECHASANCION :=SYSDATE;
END;



/*DISPARADOR OK*/
INSERT INTO SANCION VALUES(1,1040987450,NULL,30000);

/*Disparador OK*/
INSERT INTO AGENTETRANSITO VALUES(NULL,'CC',1030384590,1,'MBDA@GMAIL.COM');
INSERT INTO AGENTETRANSITO VALUES(NULL,'CC',1050876345,1,'BASES@GMAIL.COM');

/*DISPARADOR OK*/
DELETE CIUDADANO;

/*DISPARADOR OK*/
DELETE SANCION;

/*Disparador OK*/
INSERT INTO SITIO VALUES(NULL,'CUNDINAMARCA','BOGOTÁ','CALLE 200');

/*DISPARADOR OK*/
INSERT INTO CIUDADANO VALUES(1090876456,'CC','FELIPE','FERRARI@GMAIL.COM',NULL);

/*Disparador OK*/
INSERT INTO SANCION VALUES(NULL,'A',24,1,'BOGOTÁ');

/*DISPARADOR NOOK*/
INSERT INTO CIUDADANO VALUES(1090876456,'CC','FELIPE','FERRARI@GMAIL.COM',3116723465);