------------------PK---------------

ALTER TABLE VEHICULO ADD CONSTRAINT PK_VEHICULO PRIMARY KEY(PLACA);
ALTER TABLE AGENTETRANSITO ADD CONSTRAINT PK_AGENTETRANSITO PRIMARY KEY(IDAGENTE);
ALTER TABLE CIUDADANO ADD CONSTRAINT PK_CIUDADANO PRIMARY KEY(NUMEROID);
ALTER TABLE SANCION ADD CONSTRAINT PK_SANCION PRIMARY KEY(IDSANCION);
ALTER TABLE TIENE ADD CONSTRAINT PK_TIENE PRIMARY KEY(SANCION,CIUDADANO);
ALTER TABLE SITIO ADD CONSTRAINT PK_SITIO PRIMARY KEY(IDSITIO);

------------------FK---------------

ALTER TABLE VEHICULO ADD CONSTRAINT FK_VEHICULO_AGENTETRANSITO FOREIGN KEY(AGENTE) REFERENCES AGENTETRANSITO(IDAGENTE) ;
ALTER TABLE VEHICULO ADD CONSTRAINT FK_VEHICULO_CIUDADANO FOREIGN KEY(CIUDADANO) REFERENCES CIUDADANO(NUMEROID) ;

ALTER TABLE SANCION ADD CONSTRAINT FK_SANCION_AGENTETRANSITO FOREIGN KEY(AGENTE) REFERENCES AGENTETRANSITO(IDAGENTE) ;
ALTER TABLE SANCION ADD CONSTRAINT FK_SANCION_SITIO FOREIGN KEY(CIUDAD) REFERENCES SITIO(IDSITIO);

ALTER TABLE TIENE ADD CONSTRAINT FK_TIENE_SANCION FOREIGN KEY(SANCION) REFERENCES SANCION(IDSANCION);
ALTER TABLE TIENE ADD CONSTRAINT FK_TIENE_CIUDADANO FOREIGN KEY(CIUDADANO) REFERENCES CIUDADANO(NUMEROID);


------------------UK---------------

ALTER TABLE CIUDADANO ADD CONSTRAINT UK_CIUDADANO UNIQUE(TELEFONO);